packages:
  - "packages/*"
virtualStoreDirMaxLength: 120
hoistPattern:
  - "*"
publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": false
  esbuild: true
  prisma: false
  unrs-resolver: true
